--Author: Julia H. Pohl

CREATE SCHEMA IF NOT EXISTS weather_predict_db;

--code for resetting, uncomment and run to drop and recreate tables
/*
  DROP VIEW IF EXISTS wx_time_features;
  DROP TABLE IF EXISTS wx_data CASCADE;
  DROP TABLE IF EXISTS wmo_codes CASCADE;
  DROP TABLE IF EXISTS cities CASCADE;
  DROP TABLE IF EXISTS admin_div_1 CASCADE;
  DROP TABLE IF EXISTS states CASCADE;
*/

--TABLES

CREATE TABLE IF NOT EXISTS weather_predict_db.states (
  state_id          int           generated by default as identity (start with 1),
  state_name_long   varchar(60)   NOT NULL,
  state_name_short  varchar(40)   ,
  state_abbr        char(3)       NOT NULL, --use ISO 3-letter code
  CONSTRAINT states_pk PRIMARY KEY (state_id)
);
CREATE TABLE IF NOT EXISTS weather_predict_db.admin_div_1 (
  div1_id           int           generated by default as identity (start with 1),
  div1_name         varchar(60)   NOT NULL,
  div1_abbr         char(4)       ,
  state_id          int           NOT NULL,
  CONSTRAINT admin_div_1_pk PRIMARY KEY (div1_id),
  CONSTRAINT adm_div1_states_fk FOREIGN KEY (state_id) REFERENCES weather_predict_db.states(state_id)
);
CREATE TABLE IF NOT EXISTS weather_predict_db.cities (
  city_id           int           generated by default as identity (start with 1),
  city_name         varchar(60)   NOT NULL,
  div1_id           int           NOT NULL,
  CONSTRAINT cities_pk PRIMARY KEY (city_id),
  CONSTRAINT cities_adm_div1_fk FOREIGN KEY (div1_id) REFERENCES weather_predict_db.admin_div_1(div1_id)
);
CREATE TABLE IF NOT EXISTS weather_predict_db.wmo_codes (
  wmo_code          char(2)       , --primary key
  wmo_text          varchar(40)   NOT NULL,
  CONSTRAINT wmo_codes_pk PRIMARY KEY (wmo_code)
);
CREATE TABLE IF NOT EXISTS weather_predict_db.wx_data (
  data_id           int           generated by default as identity (start with 1),
  city_id           int           NOT NULL,
  dtg               timestamp with time zone    NOT NULL,
  temp_C            decimal(4,1)  ,
  humidity          decimal(3,2)  ,
  precip_chance     decimal(3,2)  ,
  precip_mm         int           ,
  wmo_code          char(2)       ,
  CONSTRAINT wx_data_pk PRIMARY KEY (data_id),
  CONSTRAINT wx_data_cities_fk FOREIGN KEY (city_id)  REFERENCES weather_predict_db.cities(city_id),
  CONSTRAINT wx_data_wmo_fk    FOREIGN KEY (wmo_code) REFERENCES weather_predict_db.wmo_codes(wmo_code),
  CONSTRAINT wx_data_dtg_range      CHECK ((dtg >= '2017-01-01 00:00:00' )),
    --Open-Meteo hourly data in current API format is only available back to 2017
  CONSTRAINT wx_data_temp_range     CHECK ((temp_C between -150.0 and 100.0)),
  CONSTRAINT wx_data_precipch_range CHECK ((precip_chance between 0.0 and 1.0)), 
  CONSTRAINT wx_data_precipmm_range CHECK ((precip_mm >= 0))
);

--QUERIES

CREATE OR REPLACE VIEW weather_predict_db.wx_time_features as
  WITH Criteria as
    (SELECT w.data_id,
      w.dtg as end_date,
      w.dtg - INTERVAL '30 days' as begin_date,
      w.city_id
      FROM weather_predict_db.wx_data w),
  Averages as
    (SELECT AVG(d.temp_C) as avg_temp_C_30day,
      AVG(d.humidity) as avg_humidity_30day,
      AVG(d.precip_mm) as avg_precip_mm_30day
      FROM weather_predict_db.wx_data d, Criteria c
      WHERE d.dtg BETWEEN c.begin_date AND c.end_date
        AND d.city_id = c.city_id)
  SELECT c.data_id, c.city_id, c.end_date as dtg, a.*
  FROM Criteria c, Averages a
  ORDER BY c.data_id;
